# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 20:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20160629_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_created',
            field=models.DateField(default=datetime.date(2016, 6, 30)),
        ),
    ]
