# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 21:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_title', models.CharField(max_length=250)),
                ('report_date', models.DateField(auto_now_add=True)),
                ('content', models.TextField(max_length=1000)),
                ('activity', models.CharField(choices=[('attended', 'Attended an Event'), ('organized', 'Organized an Event'), ('coorganized', 'Helped Organize an Event with a fellow Ambassador')], max_length=11)),
                ('activity_date', models.DateField()),
                ('created_by', models.CharField(max_length=100)),
                ('test', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
