# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 23:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reports',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='reports',
            name='test',
        ),
    ]
