# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_remove_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='name', max_length=100),
        ),
    ]
