# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_userprofile_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.TextField(default='menlo park, US'),
            preserve_default=False,
        ),
    ]
