# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_userprofile_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentor', models.CharField(max_length=100)),
                ('mentee', models.CharField(max_length=100)),
            ],
        ),
    ]
