# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_mentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='mentee',
            field=models.CharField(choices=[('attended', 'Attended an Event'), ('organized', 'Organized an Event'), ('coorganized', 'Helped Organize an Event with a fellow Ambassador')], max_length=100),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='mentor',
            field=models.CharField(choices=[('attended', 'Attended an Event'), ('organized', 'Organized an Event'), ('coorganized', 'Helped Organize an Event with a fellow Ambassador')], max_length=100),
        ),
    ]
