# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_auto_20160711_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='mentee',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='mentor',
            field=models.CharField(max_length=100),
        ),
    ]
