# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 00:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_auto_20160712_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='mentee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mentors', to='user_profile.UserProfile'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mentees', to='user_profile.UserProfile'),
        ),
    ]
